[package]
name = "honeysearch"
version = "0.1.0"
authors = ["Giovanni Capuano <webmaster@giovannicapuano.net>"]

[dependencies]
rustc-serialize = "0.3"
postgres       = "0.11"
postgres_array = "0.6"
rs-es  = { git = "https://github.com/benashford/rs-es" }
chrono = "0.2"
iron   = "0.2"
router = "0.1"
params = "0.0.3"
