[package]
name    = "honeysearch"
version = "0.1.0"

authors = ["Giovanni Capuano <webmaster@giovannicapuano.net>"]
license = "BSD-2-Clause"

[dependencies]
rustc-serialize = "0.3"
postgres        = "0.11"
postgres_array  = "0.6"
chrono          = "0.2"
iron            = "0.2"
router          = "0.1"
params          = "0.0.3"
toml            = "0.1"
lazy_static     = "0.1"

[dependencies.rs-es]
git = "https://github.com/benashford/rs-es"

[lib]
name = "honeysearch"
path = "src/lib.rs"

[[bin]]
name = "honeysearch"
path = "src/main.rs"
doc  = false
