[package]
name    = "searchspot"
version = "0.1.0"

authors = ["Giovanni Capuano <webmaster@giovannicapuano.net>"]
license = "BSD-2-Clause"

[dependencies]
rustc-serialize = "0.3"
chrono          = "0.2"
iron            = "0.2"
router          = "0.1"
logger          = "0.0.3"
params          = "0.0.3"
toml            = "0.1"
lazy_static     = "0.1"

[dependencies.rs-es]
git = "https://github.com/benashford/rs-es"

[lib]
name = "searchspot"
path = "src/lib.rs"

[[bin]]
name = "searchspot"
path = "src/main.rs"
doc  = false

[target.heroku]
version = "stable"
