[package]
name    = "searchspot"
version = "0.4.0"

authors = ["Giovanni Capuano <webmaster@giovannicapuano.net>"]
license = "BSD-2-Clause"

build   = "build.rs"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]

[dependencies]
chrono       = "0.2"

iron         = "0.4"
router       = "0.2"
logger       = "0.1"
params       = "0.3"

lazy_static  = "0.2"
maplit       = "0.1"
oath         = "0.1"
log          = "0.3"

serde        = "=0.7.14"
serde_json   = "0.7"
serde_macros = { version = "=0.7.11", optional = true }

[build-dependencies]
serde_codegen = { version = "=0.7.14", optional = true }

[dependencies.toml]
version  = "0.1"
features = ["serde"]
default-features = false

[dependencies.rs-es]
version  = "0.4"
features = ["default_without_ssl"]
default-features = false

[lib]
name = "searchspot"
path = "src/lib.rs"

[[bin]]
name = "searchspot"
path = "src/main.rs"
doc  = false
