[es]
url   = "https://user:pass@example.com:80"
index = "my_index"

[http]
host = "0.0.0.0"
port = 3001

[auth]
enabled = true
read    = "icsbqwdg7ukqluav"
write   = "7x2ockhyff4fmm5n"

[monitor]
provider     = "rollbar"
enabled      = true
access_token = "secret"
environment  = "production"

[tokens]
[tokens.lifetime]
read  = 30
write = 30
